version: '3.1'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./integration_service
      dockerfile: Dockerfile
    container_name: integration-service
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "integration_service.create_app:create_app()"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - flask-app
  kafka:
    build:
      context: ./kafka_controller
      dockerfile: Dockerfile
    container_name: kafka-controller
    network_mode: host
networks:
  my-network: